### PR TITLE
feat: update pkgs to pull flannel CNI plugin 1.0.1

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/talos-systems/pkgs/pull/425

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Review by Ulexus — APPROVED** [review]

**Comment by Ulexus** [comment]
Note that this actually pulls 1.1.0, not 1.0.1

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
> Note that this actually pulls 1.1.0, not 1.0.1

I can't see that... should be 1.0.1

**Comment by Ulexus** [comment]
Yep; ignore me.

**Comment by smira** [comment]
indirectly updated via #43

**Pull request closed without merging**
